import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { ReceivingStatusProvider } from "@/context/ReceivingSideStatusContext";
import { WebRTCProvider } from "@/context/WebRTCContext";
import { SenderStatusProvider } from "@/context/SenderSideStatusContext";
import { SendFileDataProvider } from "@/context/SendFileDataContext";
import { ReceiveFileDataProvider } from "@/context/ReceiveFileDataContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <WebRTCProvider>
          <SenderStatusProvider>
            <ReceivingStatusProvider>
              <SendFileDataProvider>
                <ReceiveFileDataProvider>
                  {children}
                </ReceiveFileDataProvider>
              </SendFileDataProvider>
            </ReceivingStatusProvider>
          </SenderStatusProvider>
        </WebRTCProvider>
      </body>
    </html>
  );
}
